// COMRebarPos.idl : IDL source for COMRebarPos.dll
//
// Type library section and components
//
[
#if REBARPOS2015
	uuid(26E9A3B0-6567-4857-AABB-E09AC4A7A8A5),
#endif
#if REBARPOS2013
	uuid(26E9A3B0-6567-4857-AABB-E09AC4A7A8A3),
#endif	
#if REBARPOS2010
	uuid(26E9A3B0-6567-4857-AABB-E09AC4A7A8A0),
#endif	
	version(1.0),
	helpstring("RebarPos 1.0 Type Library"),
]
library COMREBARPOSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

#if REBARPOS2015
	importlib("C:\\Autodesk\\ObjectARX 2015\\inc-x64\\axdb20enu.tlb");
#endif
#if REBARPOS2013
	importlib("C:\\Autodesk\\ObjectARX 2013\\inc-x64\\axdb19enu.tlb");
#endif	
#if REBARPOS2010
	importlib("C:\\Autodesk\\ObjectARX 2010\\inc-x64\\axdb18enu.tlb");
#endif

	// This file will be processed by the MIDL tool to
	// produce the type library (COMRebarPos.tlb) and marshalling code.
	import "oaidl.idl";
	import "ocidl.idl";

	//
	// Interfaces
	//
	// IComRebarPos interface
	[
		object,
		uuid(5D19CA2D-2E6E-4dce-A7FB-DA0B7C7CD913),
		dual,
		helpstring("IComRebarPos Interface"),
		pointer_default(unique)
	]
	interface IComRebarPos : IAcadEntity
	{
		[propget, id(1), helpstring("property BasePoint")] HRESULT BasePoint([out, retval] VARIANT *pVal);
		[propput, id(1), helpstring("property BasePoint")] HRESULT BasePoint([in] VARIANT newVal);
		[propget, id(2), helpstring("property NoteGrip")] HRESULT NoteGrip([out, retval] VARIANT *pVal);
		[propput, id(2), helpstring("property NoteGrip")] HRESULT NoteGrip([in] VARIANT newVal);
		[propget, id(18), helpstring("property LengthGrip")] HRESULT LengthGrip([out, retval] VARIANT *pVal);
		[propput, id(18), helpstring("property LengthGrip")] HRESULT LengthGrip([in] VARIANT newVal);
		[propget, id(3), helpstring("property Pos")] HRESULT Pos([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property Pos")] HRESULT Pos([in] BSTR newVal);
		[propget, id(4), helpstring("property Count")] HRESULT Count([out, retval] BSTR *pVal);
		[propput, id(4), helpstring("property Count")] HRESULT Count([in] BSTR newVal);
		[propget, id(5), helpstring("property Diameter")] HRESULT Diameter([out, retval] BSTR *pVal);
		[propput, id(5), helpstring("property Diameter")] HRESULT Diameter([in] BSTR newVal);
		[propget, id(6), helpstring("property Spacing")] HRESULT Spacing([out, retval] BSTR *pVal);
		[propput, id(6), helpstring("property Spacing")] HRESULT Spacing([in] BSTR newVal);
		[propget, id(7), helpstring("property Multiplier")] HRESULT Multiplier([out, retval] long *pVal);
		[propput, id(7), helpstring("property Multiplier")] HRESULT Multiplier([in] long newVal);
		[propget, id(8), helpstring("property ShowTotalLength")] HRESULT ShowLength([out, retval] long *pVal);
		[propput, id(8), helpstring("property ShowTotalLength")] HRESULT ShowLength([in] long newVal);
		[propget, id(9), helpstring("property Note")] HRESULT Note([out, retval] BSTR *pVal);
		[propput, id(9), helpstring("property Note")] HRESULT Note([in] BSTR newVal);
		[propget, id(10), helpstring("property A")] HRESULT A([out, retval] BSTR *pVal);
		[propput, id(10), helpstring("property A")] HRESULT A([in] BSTR newVal);
		[propget, id(11), helpstring("property B")] HRESULT B([out, retval] BSTR *pVal);
		[propput, id(11), helpstring("property B")] HRESULT B([in] BSTR newVal);
		[propget, id(12), helpstring("property C")] HRESULT C([out, retval] BSTR *pVal);
		[propput, id(12), helpstring("property C")] HRESULT C([in] BSTR newVal);
		[propget, id(13), helpstring("property D")] HRESULT D([out, retval] BSTR *pVal);
		[propput, id(13), helpstring("property D")] HRESULT D([in] BSTR newVal);
		[propget, id(14), helpstring("property E")] HRESULT E([out, retval] BSTR *pVal);
		[propput, id(14), helpstring("property E")] HRESULT E([in] BSTR newVal);
		[propget, id(15), helpstring("property F")] HRESULT F([out, retval] BSTR *pVal);
		[propput, id(15), helpstring("property F")] HRESULT F([in] BSTR newVal);
		[propget, id(16), helpstring("property Length")] HRESULT Length([out, retval] BSTR *pVal);
		[propget, id(17), helpstring("property Shape")] HRESULT Shape([out, retval] BSTR *pVal);
		[propput, id(17), helpstring("property Shape")] HRESULT Shape([in] BSTR newVal);
		[propget, id(19), helpstring("property Scale")] HRESULT Scale([out, retval] double *pVal);
		[propput, id(19), helpstring("property Scale")] HRESULT Scale([in] double newVal);
		[propget, id(20), helpstring("property LengthAlignment")] HRESULT LengthAlignment([out, retval] long *pVal);
		[propput, id(20), helpstring("property LengthAlignment")] HRESULT LengthAlignment([in] long newVal);
		[propget, id(21), helpstring("property NoteAlignment")] HRESULT NoteAlignment([out, retval] long *pVal);
		[propput, id(21), helpstring("property NoteAlignment")] HRESULT NoteAlignment([in] long newVal);
	};
	//
	// coclasses in type library
	//

	// ComRebarPos coclass
	[
#if REBARPOS2015
		uuid(97CAC17D-B1C7-49ca-8D57-D3FF491860F5),
#endif
#if REBARPOS2013
		uuid(97CAC17D-B1C7-49ca-8D57-D3FF491860F3),
#endif	
#if REBARPOS2010
		uuid(97CAC17D-B1C7-49ca-8D57-D3FF491860F0),
#endif
		helpstring("ComRebarPos Class"),
		noncreatable
	]
	coclass ComRebarPos
	{
		[default] interface IComRebarPos;
		[source] interface IAcadObjectEvents;
	};

	//
	// Interfaces
	//
	// IComBOQTable interface
	[
		object,
		uuid(3E0EF436-0D8E-41a7-B33D-3B7AAD33BCDB),
		dual,
		helpstring("IComBOQTable Interface"),
		pointer_default(unique)
	]
	interface IComBOQTable : IAcadEntity
	{
		[propget, id(1), helpstring("property BasePoint")] HRESULT BasePoint([out, retval] VARIANT *pVal);
		[propput, id(1), helpstring("property BasePoint")] HRESULT BasePoint([in] VARIANT newVal);
		[propget, id(2), helpstring("property Multiplier")] HRESULT Multiplier([out, retval] long *pVal);
		[propput, id(2), helpstring("property Multiplier")] HRESULT Multiplier([in] long newVal);
		[propget, id(4), helpstring("property Scale")] HRESULT Scale([out, retval] double *pVal);
		[propput, id(4), helpstring("property Scale")] HRESULT Scale([in] double newVal);
		[propget, id(5), helpstring("property Heading")] HRESULT Heading([out, retval] BSTR *pVal);
		[propput, id(5), helpstring("property Heading")] HRESULT Heading([in] BSTR newVal);
		[propget, id(6), helpstring("property Footing")] HRESULT Footing([out, retval] BSTR *pVal);
		[propput, id(6), helpstring("property Footing")] HRESULT Footing([in] BSTR newVal);
		[propget, id(7), helpstring("property MaxRows")] HRESULT MaxRows([out, retval] long *pVal);
		[propput, id(7), helpstring("property MaxRows")] HRESULT MaxRows([in] long newVal);
		[propget, id(8), helpstring("property TableSpacing")] HRESULT TableSpacing([out, retval] double *pVal);
		[propput, id(8), helpstring("property TableSpacing")] HRESULT TableSpacing([in] double newVal);
		[propget, id(9), helpstring("property Note")] HRESULT Note([out, retval] BSTR *pVal);
		[propput, id(9), helpstring("property Note")] HRESULT Note([in] BSTR newVal);
		[propget, id(10), helpstring("property Precision")] HRESULT Precision([out, retval] long *pVal);
		[propput, id(10), helpstring("property Precision")] HRESULT Precision([in] long newVal);
		[propget, id(11), helpstring("property DisplayUnit")] HRESULT DisplayUnit([out, retval] long *pVal);
		[propput, id(11), helpstring("property DisplayUnit")] HRESULT DisplayUnit([in] long newVal);
		[propget, id(12), helpstring("property HeadingScale")] HRESULT HeadingScale([out, retval] double *pVal);
		[propput, id(12), helpstring("property HeadingScale")] HRESULT HeadingScale([in] double newVal);
		[propget, id(13), helpstring("property FootingScale")] HRESULT FootingScale([out, retval] double *pVal);
		[propput, id(13), helpstring("property FootingScale")] HRESULT FootingScale([in] double newVal);
		[propget, id(14), helpstring("property RowSpacing")] HRESULT RowSpacing([out, retval] double *pVal);
		[propput, id(14), helpstring("property RowSpacing")] HRESULT RowSpacing([in] double newVal);
	};
	//
	// coclasses in type library
	//

	// ComBOQTable coclass
	[
#if REBARPOS2015
		uuid(BA77CFFF-0274-4d4c-BFE2-64A5731BAD35),
#endif
#if REBARPOS2013
		uuid(BA77CFFF-0274-4d4c-BFE2-64A5731BAD33),
#endif	
#if REBARPOS2010
		uuid(BA77CFFF-0274-4d4c-BFE2-64A5731BAD30),
#endif
		helpstring("ComBOQTable Class"),
		noncreatable
	]
	coclass ComBOQTable
	{
		[default] interface IComBOQTable;
		[source] interface IAcadObjectEvents;
	};
};
