// compoly.idl : IDL source for compoly.dll
//
// (C) Copyright 1998-2008 by Autodesk, Inc.
// Permission to use, copy, modify, and distribute this software in
// object code form for any purpose and without fee is hereby granted, 
// provided that the above copyright notice appears in all copies and 
// that both that copyright notice and the limited warranty and
// restricted rights notice below appear in all supporting 
// documentation.
//
// AUTODESK PROVIDES THIS PROGRAM "AS IS" AND WITH ALL FAULTS. 
// AUTODESK SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF
// MERCHANTABILITY OR FITNESS FOR A PARTICULAR USE.  AUTODESK, INC. 
// DOES NOT WARRANT THAT THE OPERATION OF THE PROGRAM WILL BE
// UNINTERRUPTED OR ERROR FREE.
//
// Use, duplication, or disclosure by the U.S. Government is subject to 
// restrictions set forth in FAR 52.227-19 (Commercial Computer
// Software - Restricted Rights) and DFAR 252.227-7013(c)(1)(ii)
// (Rights in Technical Data and Computer Software), as applicable.
#include "RebarPos.hm"
//
// Type library section and components
//
[
	uuid(60E2E250-99CE-42EB-8881-54C193F35E40),
	version(1.0),
	helpstring("RebarPos 1.0 Type Library"),
	helpfile("RebarPos.hlp")
]
library COMPOLYLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//Importing english is ok here. We don't localize this idl/tlb.
	//axdb18enu.tlb is guaranteed to be available in all locales.
	//If you want to provide localized typelib then you must import
	//localized tlb here.
	importlib("axdb18enu.tlb");

	// This file will be processed by the MIDL tool to
	// produce the type library (compoly.tlb) and marshalling code.

	import "oaidl.idl";
	import "ocidl.idl";

	//
	// Interfaces
	//
	// IComPolygon interface
	[
		object,
		uuid(4EB91FA1-8DD3-4DF9-9277-E0BA3EA5361F),
		dual,
		helpstring("IComPolygon Interface"),
		helpcontext(IDH_ICOMPOLYGON),
		pointer_default(unique)
	]
	interface IComPolygon : IAcadEntity
	{
		[propget, id(1), helpstring("property BasePoint"),helpcontext(IDH_BASEPOINT)] HRESULT BasePoint([out, retval] VARIANT *pVal);
		[propput, id(1), helpstring("property BasePoint"),helpcontext(IDH_BASEPOINT)] HRESULT BasePoint([in] VARIANT newVal);
		[propget, id(2), helpstring("property NoteGrip"),helpcontext(IDH_NOTEGRIP)] HRESULT NoteGrip([out, retval] VARIANT *pVal);
		[propput, id(2), helpstring("property NoteGrip"),helpcontext(IDH_NOTEGRIP)] HRESULT NoteGrip([in] VARIANT newVal);
		[propget, id(3), helpstring("property Pos"),helpcontext(IDH_POS)] HRESULT Pos([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property Pos"),helpcontext(IDH_POS)] HRESULT Pos([in] BSTR newVal);
		[propget, id(4), helpstring("property Count"),helpcontext(IDH_COUNT)] HRESULT Count([out, retval] BSTR *pVal);
		[propput, id(4), helpstring("property Count"),helpcontext(IDH_COUNT)] HRESULT Count([in] BSTR newVal);
		[propget, id(5), helpstring("property Diameter"),helpcontext(IDH_DIAMETER)] HRESULT Diameter([out, retval] BSTR *pVal);
		[propput, id(5), helpstring("property Diameter"),helpcontext(IDH_DIAMETER)] HRESULT Diameter([in] BSTR newVal);
		[propget, id(6), helpstring("property Spacing"),helpcontext(IDH_SPACING)] HRESULT Spacing([out, retval] BSTR *pVal);
		[propput, id(6), helpstring("property Spacing"),helpcontext(IDH_SPACING)] HRESULT Spacing([in] BSTR newVal);
		[propget, id(7), helpstring("property Multiplier"),helpcontext(IDH_MULTIPLIER)] HRESULT Multiplier([out, retval] long *pVal);
		[propput, id(7), helpstring("property Multiplier"),helpcontext(IDH_MULTIPLIER)] HRESULT Multiplier([in] long newVal);
		[propget, id(8), helpstring("property ShowLength"),helpcontext(IDH_SHOWLENGTH)] HRESULT ShowLength([out, retval] VARIANT_BOOL *pVal);
		[propput, id(8), helpstring("property ShowLength"),helpcontext(IDH_SHOWLENGTH)] HRESULT ShowLength([in] VARIANT_BOOL newVal);
		[propget, id(9), helpstring("property Note"),helpcontext(IDH_NOTE)] HRESULT Note([out, retval] BSTR *pVal);
		[propput, id(9), helpstring("property Note"),helpcontext(IDH_NOTE)] HRESULT Note([in] BSTR newVal);
		[propget, id(10), helpstring("property A"),helpcontext(IDH_A)] HRESULT A([out, retval] BSTR *pVal);
		[propput, id(10), helpstring("property A"),helpcontext(IDH_A)] HRESULT A([in] BSTR newVal);
		[propget, id(11), helpstring("property B"),helpcontext(IDH_B)] HRESULT B([out, retval] BSTR *pVal);
		[propput, id(11), helpstring("property B"),helpcontext(IDH_B)] HRESULT B([in] BSTR newVal);
		[propget, id(12), helpstring("property C"),helpcontext(IDH_C)] HRESULT C([out, retval] BSTR *pVal);
		[propput, id(12), helpstring("property C"),helpcontext(IDH_C)] HRESULT C([in] BSTR newVal);
		[propget, id(13), helpstring("property D"),helpcontext(IDH_D)] HRESULT D([out, retval] BSTR *pVal);
		[propput, id(13), helpstring("property D"),helpcontext(IDH_D)] HRESULT D([in] BSTR newVal);
		[propget, id(14), helpstring("property E"),helpcontext(IDH_E)] HRESULT E([out, retval] BSTR *pVal);
		[propput, id(14), helpstring("property E"),helpcontext(IDH_E)] HRESULT E([in] BSTR newVal);
		[propget, id(15), helpstring("property F"),helpcontext(IDH_F)] HRESULT F([out, retval] BSTR *pVal);
		[propput, id(15), helpstring("property F"),helpcontext(IDH_F)] HRESULT F([in] BSTR newVal);
		[propget, id(16), helpstring("property Length"),helpcontext(IDH_LENGTH)] HRESULT Length([out, retval] BSTR *pVal);
		[propget, id(17), helpstring("property Shape"),helpcontext(IDH_SHAPE)] HRESULT Shape([out, retval] BSTR *pVal);
		[propput, id(17), helpstring("property Shape"),helpcontext(IDH_SHAPE)] HRESULT Shape([in] BSTR newVal);
		[propget, id(18), helpstring("property Group"),helpcontext(IDH_GROUP)] HRESULT Group([out, retval] BSTR *pVal);
		[propput, id(18), helpstring("property Group"),helpcontext(IDH_GROUP)] HRESULT Group([in] BSTR newVal);
	};
	//
	// coclasses in type library
	//

	// ComPolygon coclass
	[
		uuid(6421F67D-6A0A-4CA4-85BA-F11A0852A656),
		helpstring("ComPolygon Class"),
		helpcontext(IDH_CCOMPOLYGON),
		noncreatable
	]
	coclass ComPolygon 
	{
		[default] interface IComPolygon;
		[source] interface IAcadObjectEvents;
	};
};
