//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebarPosCommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebarPosCommands.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METRAJ.
        /// </summary>
        internal static string BOQ_Local {
            get {
                return ResourceManager.GetString("BOQ_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METRAJEDIT.
        /// </summary>
        internal static string BOQEDIT_Local {
            get {
                return ResourceManager.GetString("BOQEDIT_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZKOPYALA.
        /// </summary>
        internal static string COPYPOS_Local {
            get {
                return ResourceManager.GetString("COPYPOS_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZKOPYALADETAY.
        /// </summary>
        internal static string COPYPOSDETAIL_Local {
            get {
                return ResourceManager.GetString("COPYPOSDETAIL_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZBENZET.
        /// </summary>
        internal static string COPYPOSNUMBER_Local {
            get {
                return ResourceManager.GetString("COPYPOSNUMBER_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMARASIL.
        /// </summary>
        internal static string EMPTYPOS_Local {
            get {
                return ResourceManager.GetString("EMPTYPOS_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEKILSIL.
        /// </summary>
        internal static string HIDESHAPES_Local {
            get {
                return ResourceManager.GetString("HIDESHAPES_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZKATKI.
        /// </summary>
        internal static string INCLUDEPOS_Local {
            get {
                return ResourceManager.GetString("INCLUDEPOS_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SONPOZ.
        /// </summary>
        internal static string LASTPOSNUMBER_Local {
            get {
                return ResourceManager.GetString("LASTPOSNUMBER_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZEKLE.
        /// </summary>
        internal static string NEWPOS_Local {
            get {
                return ResourceManager.GetString("NEWPOS_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZNUM.
        /// </summary>
        internal static string NUMBERPOS_Local {
            get {
                return ResourceManager.GetString("NUMBERPOS_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZ.
        /// </summary>
        internal static string POS_Local {
            get {
                return ResourceManager.GetString("POS_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZKONTROL.
        /// </summary>
        internal static string POSCHECK_Local {
            get {
                return ResourceManager.GetString("POSCHECK_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZEDIT.
        /// </summary>
        internal static string POSEDIT_Local {
            get {
                return ResourceManager.GetString("POSEDIT_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZBUL.
        /// </summary>
        internal static string POSFIND_Local {
            get {
                return ResourceManager.GetString("POSFIND_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POZGRUP.
        /// </summary>
        internal static string POSGROUP_Local {
            get {
                return ResourceManager.GetString("POSGROUP_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METRAJYARDIM.
        /// </summary>
        internal static string POSHELP_Local {
            get {
                return ResourceManager.GetString("POSHELP_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOYGOSTER.
        /// </summary>
        internal static string POSLENGTH_Local {
            get {
                return ResourceManager.GetString("POSLENGTH_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACILIMLAR.
        /// </summary>
        internal static string POSSHAPES_Local {
            get {
                return ResourceManager.GetString("POSSHAPES_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEKILGOSTER.
        /// </summary>
        internal static string SHOWSHAPES_Local {
            get {
                return ResourceManager.GetString("SHOWSHAPES_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLOSTILI.
        /// </summary>
        internal static string TABLESTYLE_Local {
            get {
                return ResourceManager.GetString("TABLESTYLE_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEKILGOSTERGIZLE.
        /// </summary>
        internal static string TOGGLESHAPES_Local {
            get {
                return ResourceManager.GetString("TOGGLESHAPES_Local", resourceCulture);
            }
        }
    }
}
